[features]
seeds = false

[programs.localnet]
swap_base = "9ctuy1ovKd6Mk1ugjoh936CrNCbsfRs7UFJQM32MxYoq"

[programs.devnet]
stable_swap = "9ctuy1ovKd6Mk1ugjoh936CrNCbsfRs7UFJQM32MxYoq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/coredev0927/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
