[features]
seeds = false
[programs.localnet]
swap_base = "BrxSF554tzDU6j1GNw4JyhHPV1XYmez1xfhGJTVkL8Vj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/olaf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
