[features]
seeds = false

[programs.localnet]
swap_base = "91UuzKJN9pGvpvPuMZmaRXvHbU8ND7y1ZdMj6rgiXcfS"

[programs.devnet]
stable_swap = "91UuzKJN9pGvpvPuMZmaRXvHbU8ND7y1ZdMj6rgiXcfS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/olaf45/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
